version: '1.0'

services:
 mysql:
  container_name: dmcli-database
  image: mysql:latest
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: 'urubu100'
   MYSQL_DATABASE: 'db_dmcli'
  volumes:
    - ./init-scripts:/docker-entrypoint-initdb.d
  ports:
    - 3306:3306
 app:
  container_name: dmcli-app
  image: dmcli
  tty: true
  volumes:
   - ./target:/home
  links:
   - mysql
  ports:
   - '8080:8080'
 
volumes:
  dmcli-datavolume:
  dmcli-app:

