version: '2.0'

services:
 mysql:
  container_name: dmcli-database
  image: mysql:5.7
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: 'urubu100'
   MYSQL_DATABASE: 'db_dmcli'
  volumes:
    - ./init-scripts:/docker-entrypoint-initdb.d
  ports:
    - "3306:3306"

 app:
  container_name: dmcli-app
  image: openjdk:17-jdk-slim
  working_dir: /home
  tty: true
  volumes:
   - ./target:/home 
volumes:
  dmcli-database:

